#!/usr/bin/env python3
"""Builds docs/eula/index.html from the product's legal/EULA.md.

The licence text lives with the product, in the private repository, next to
the code it describes. This page is a rendering of it, never an edited copy:
change the wording there, then run

    python3 make-eula.py

Only the "# English" and "# 日本語" parts are published. Everything else in
that file is internal notes and stays out.

It expects this repository to be checked out as lp-site/ inside the product's
folder, which is how it is kept (the same arrangement as caps REC and
LUFSBar Pro).
"""
import html
import re
import shutil
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parent / "legal" / "EULA.md"
NOTICES = HERE.parent / "legal" / "THIRD_PARTY_NOTICES.txt"
OUT = HERE / "docs" / "eula" / "index.html"


def part(lines, title):
    """The lines under a top-level heading, up to the next horizontal rule."""
    start = lines.index(title) + 1
    end = next(i for i in range(start, len(lines)) if lines[i].strip() == "---")
    return lines[start:end]


def inline(text):
    text = html.escape(text, quote=False)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", text)
    text = text.replace("THIRD_PARTY_NOTICES.txt",
                        '<a href="THIRD_PARTY_NOTICES.txt">THIRD_PARTY_NOTICES.txt</a>')
    return text


def sections(lines):
    """[(number, title, [blocks])], and the lines before the first section.
    A block is ("p", text) or ("ul", [items])."""
    head, out, cur = [], [], None
    for raw in lines:
        line = raw.rstrip()
        m = re.match(r"^## (\d+)\. (.+)$", line)
        if m:
            cur = (int(m.group(1)), m.group(2), [])
            out.append(cur)
            continue
        blocks = cur[2] if cur else head
        if not line:
            blocks.append(None)
        elif line.startswith("- "):
            if blocks and blocks[-1] and blocks[-1][0] == "ul":
                blocks[-1][1].append(line[2:])
            else:
                blocks.append(("ul", [line[2:]]))
        elif blocks and blocks[-1] and blocks[-1][0] == "p":
            blocks[-1] = ("p", blocks[-1][1] + " " + line)
        else:
            blocks.append(("p", line))
    clean = lambda bs: [b for b in bs if b]
    return clean(head), [(n, t, clean(bs)) for n, t, bs in out]


def render(blocks):
    out = []
    for kind, body in blocks:
        if kind == "p":
            out.append(f"<p>{inline(body)}</p>")
        else:
            out.append("<ul>" + "".join(f"<li>{inline(i)}</li>" for i in body) + "</ul>")
    return "\n    ".join(out)


def main():
    lines = SOURCE.read_text(encoding="utf-8").splitlines()
    _, en = sections(part(lines, "# English"))
    ja_head, ja = sections(part(lines, "# 日本語"))
    assert [n for n, _, _ in en] == [n for n, _, _ in ja], "the two languages must have the same sections"

    # The Japanese section 15 says its list is the English one. Show that list
    # there too, so a reader who has switched to Japanese is not sent away to
    # find it; the sentence it replaces is exactly this pointer.
    en15 = next(b for n, _, bs in en if n == 15 for b in bs if b[0] == "ul")
    for n, _, bs in ja:
        if n == 15:
            i = next(i for i, b in enumerate(bs) if b[0] == "p" and b[1].startswith("（一覧は英語版"))
            ijg = re.search(r"\*[^*]+\*", bs[i][1]).group(0)
            bs[i:i + 1] = [en15, ("p", ijg)]

    body = []
    for (n, t_en, b_en), (_, t_ja, b_ja) in zip(en, ja):
        body.append(f"""<section id="s{n}">
  <h2><span class="n">{n:02d}</span><span class="en">{inline(t_en)}</span><span class="ja">{inline(t_ja)}</span></h2>
  <div class="en">
    {render(b_en)}
  </div>
  <div class="ja">
    {render(b_ja)}
  </div>
</section>""")

    ja_note = render(ja_head)
    page = TEMPLATE.replace("{{BODY}}", "\n\n".join(body)).replace("{{JA_NOTE}}", ja_note)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(page, encoding="utf-8")
    shutil.copyfile(NOTICES, OUT.parent / "THIRD_PARTY_NOTICES.txt")
    print(f"wrote {OUT} ({len(en)} sections) and THIRD_PARTY_NOTICES.txt")


TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Generated by make-eula.py from the product's legal/EULA.md. Do not edit by hand. -->
<title>EQ Mirror — Licence</title>
<meta name="description" content="End User License Agreement for EQ Mirror.">
<meta name="theme-color" content="#eceef0">
<meta name="color-scheme" content="light">
<link rel="canonical" href="https://tokyomeltdown.github.io/eq-mirror/eula/">
<meta name="robots" content="index,follow">
<meta property="og:type" content="website">
<meta property="og:title" content="EQ Mirror — Licence">
<meta property="og:description" content="End User License Agreement for EQ Mirror.">
<meta property="og:url" content="https://tokyomeltdown.github.io/eq-mirror/eula/">
<meta property="og:image" content="https://tokyomeltdown.github.io/eq-mirror/og-image.png">
<meta property="og:site_name" content="tokyomeltdown">
<meta name="twitter:card" content="summary_large_image">
<link rel="icon" href="../favicon.svg" type="image/svg+xml">
<link rel="icon" href="../icon.png" type="image/png">
<style>
  :root{
    --bg:#eceef0; --panel:#f5f6f7; --line:rgba(60,66,72,.14);
    --fg:#1b1f23; --fg2:#4d545b; --fg3:#878e96;
  }
  *{box-sizing:border-box;margin:0;padding:0}
  html{scroll-behavior:smooth}
  body{background:var(--bg);color:var(--fg);line-height:1.7;font-size:16px;letter-spacing:.004em;
    font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text","Hiragino Sans","Noto Sans JP",sans-serif;
    -webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
  a{color:inherit}
  .wrap{max-width:760px;margin:0 auto;padding:0 28px}
  .en,.ja{display:none}
  body.lang-en .en{display:initial} body.lang-ja .ja{display:initial}
  body.lang-en h1 .en,body.lang-ja h1 .ja,
  body.lang-en div.en,body.lang-ja div.ja{display:block}

  nav{position:sticky;top:0;z-index:30;background:rgba(236,238,240,.78);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}
  nav .wrap{display:flex;align-items:center;justify-content:space-between;height:54px;max-width:1040px}
  .brand{display:flex;align-items:center;gap:9px;font-size:15px;text-decoration:none}
    .brand b{font-weight:700} .brand i{font-style:normal;opacity:.72}
  .lang{display:flex;border:1px solid var(--line);border-radius:999px;overflow:hidden}
  .lang button{background:none;border:0;color:var(--fg3);font:inherit;font-size:12px;padding:4px 12px;cursor:pointer}
  .lang button.on{background:var(--fg);color:#fff}

  header{padding:72px 0 34px;border-bottom:1px solid var(--line)}
  h1{font-size:clamp(30px,5vw,42px);line-height:1.18;letter-spacing:-.02em;font-weight:600}
  .meta{margin-top:14px;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:12px;letter-spacing:.08em;color:var(--fg3)}
  .jnote{margin-top:18px;font-size:14px;color:var(--fg2)}

  main{padding:12px 0 40px}
  section{padding:30px 0;border-bottom:1px solid var(--line)}
  section:last-of-type{border-bottom:0}
  h2{font-size:19px;font-weight:600;letter-spacing:-.01em;margin-bottom:12px}
  h2 .n{color:var(--fg3);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:13px;margin-right:10px;font-weight:400}
  body.lang-en h2 .en,body.lang-ja h2 .ja{display:inline}
  p{color:var(--fg2);margin-bottom:12px}
  p:last-child{margin-bottom:0}
  strong{color:var(--fg);font-weight:600}
  code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.86em;color:var(--fg);background:var(--panel);border:1px solid var(--line);border-radius:5px;padding:1px 5px;word-break:break-all}
  ul{margin:0 0 12px 20px;color:var(--fg2)}
  li{margin-bottom:7px}

  footer{padding:44px 0 72px;border-top:1px solid var(--line);color:var(--fg3);font-size:13px}
  footer a{margin-right:20px;color:var(--fg2);text-decoration:none}
  footer a:hover{color:var(--fg)}
  @media(max-width:560px){ body{font-size:15px} header{padding:52px 0 28px} }
</style>
</head>
<body class="lang-en">

<nav><div class="wrap">
  <a class="brand" href="../"><svg width="22" height="20" viewBox="-2 0 24 22" fill="none" stroke-linecap="round" stroke="#3c4248" aria-hidden="true"><line x1="-1" y1="11" x2="21" y2="11" stroke-opacity=".22" stroke-width=".8"/><path d="M0 13 C4 13 6 19 10 19 C14 19 16 15 20 15" stroke-opacity=".32" stroke-width="1.7"/><path d="M0 9 C4 9 6 3 10 3 C14 3 16 7 20 7" stroke-width="1.7"/></svg><span><b>EQ</b> <i>Mirror</i></span></a>
  <div class="lang"><button id="btn-en" class="on">EN</button><button id="btn-ja">日本語</button></div>
</div></nav>

<header><div class="wrap">
  <h1><span class="en">End User License Agreement</span><span class="ja">使用許諾契約</span></h1>
  <p class="meta">EQ MIRROR · VERSION 1.0 · 2026-09-27</p>
  <div class="ja jnote">{{JA_NOTE}}</div>
</div></header>

<main><div class="wrap">

{{BODY}}

</div></main>

<footer><div class="wrap">
  <a href="../"><span class="en">EQ Mirror</span><span class="ja">EQ Mirror</span></a>
  <a href="THIRD_PARTY_NOTICES.txt"><span class="en">Third-party notices</span><span class="ja">第三者ライセンス表記</span></a>
  <a href="mailto:tokyomeltdown.ai@gmail.com?subject=EQ%20Mirror%20support"><span class="en">Support</span><span class="ja">サポート</span></a>
  <p style="margin-top:16px">© 2026 tokyomeltdown</p>
</div></footer>

<script>
(function(){
  function setLang(l){
    document.body.className='lang-'+l;
    document.documentElement.lang=l;
    document.getElementById('btn-en').classList.toggle('on',l==='en');
    document.getElementById('btn-ja').classList.toggle('on',l==='ja');
    try{localStorage.setItem('eqmirror-lang',l);}catch(e){}
  }
  document.getElementById('btn-en').onclick=function(){setLang('en')};
  document.getElementById('btn-ja').onclick=function(){setLang('ja')};
  var saved=null;
  try{saved=localStorage.getItem('eqmirror-lang');}catch(e){}
  // ?lang=en or ?lang=ja wins, so a link can be shared in a given language.
  var asked=(location.search.match(/[?&]lang=(en|ja)\b/)||[])[1];
  setLang(asked || saved || ((navigator.language||'').indexOf('ja')===0?'ja':'en'));
})();
</script>
</body>
</html>
"""

if __name__ == "__main__":
    main()
